# Auto-generated from DefaultApplianceSeeder.php
# Complete appliance count mappings for all TIS devices

DEVICE_APPLIANCE_COUNTS = {
    'TIS-DMX-48': {'rgbw': 5},
    'TIS-4DI-IN': {'binary_sensor': 4},
    'HVAC6-3A-T': {},
    'TIS-PIR-CM': {'binary_sensor': 1},
    'TIS-IR-CUR': {'ac': 1},
    'ES-10F-CM': {'binary_sensor': 1, 'ac': 1},
    'RLY-4CH-10A': {'switch': 4},
    'VLC-6CH-3A': {'switch': 6},
    'RLY-8CH-16A': {'switch': 8},
    'VLC-12CH-10A': {'switch': 12},
    'DIM-6CH-2A': {'dimmer': 6},
    'DIM-4CH-3A': {'dimmer': 4},
    'DIM-2CH-6A': {'dimmer': 2},
    'TIS-AUT-TMR': {},
    'IP-COM-PORT-OLD': {},
    'TIS-SEC-SM': {'security': 1},
    'TER-4G': {},
    'TER-ACT': {'ac': 1},
    'TER-AUD': {},
    'MRS-4G': {},
    'MRS-8G': {},
    'MRS-12G': {},
    'MRS-AC10G': {'ac': 1},
    'DALI-64': {'dimmer': 12},
    'TIS-DIM-4CH-1A': {'dimmer': 4},
    'DIM-TE-2CH-3A': {'dimmer': 2},
    'DIM-TE-4CH-1.5A': {'dimmer': 4},
    'RCU-8OUT-8IN': {'switch': 8, 'binary_sensor': 8},
    'RLY-6CH-0-10V': {'dimmer': 6},
    'LUNA-TFT-43': {'ac': 1},
    'LUNA-9GANGS': {},
    'LUNA-BEDSIDE': {'ac': 1},
    'LUNA-BELL-3S': {},
    'TIS-M3-MOTOR': {'motor': 1},
    'IO-8G': {},
    'IO-AC-4G': {'ac': 1},
    'VEN-6S-BUS': {},
    'TIT-2G-BUS': {},
    'TIT-3G-BUS': {},
    'TIT-4G-BUS': {},
    'TARIQ-8G6R5Z': {},
    'TARIQ-8G3R5Z1F': {},
    'TARIQ-8G3R5Z2D': {},
    'TIS-HEALTH-CM': {},
    'VEN-2S-BUS': {},
    'VEN-3S-BUS': {},
    'VEN-4S-BUS': {},
    'VEN-AC-3R-HC-BUS': {},
    'VEN-AC-4R-HC-BUS': {},
    'VEN-AC-5R-LC-BUS': {},
    'RCU-24R20Z': {'switch': 24, 'binary_sensor': 20},
    'TIT-TFT-BUS': {'ac': 1},
    'RCU-20R20Z-IP': {'switch': 20, 'binary_sensor': 20},
    'ACM-1D-2Z': {},
    'TIS-4T-IN': {'ac': 1},
    'DIM-W06CH10A-TE': {},
    'DIM-W12CH10A-TE': {},
    'MINI-AIR-AUTO-IRE-T': {'ac': 1},
    'BUS-PIR-CM': {'binary_sensor': 1},
    'BUS-ES-IR': {'binary_sensor': 1, 'ac': 1},
    'ADS-3R-BUS': {'switch': 3},
    'ACM-3Z-IN': {'binary_sensor': 3},
    'AIR-AUTO-IRE-T': {'ac': 1},
    'BUS-AUTO-IRE-T': {'ac': 1},
    'AIR-ES-IR': {'binary_sensor': 1, 'ac': 1},
    'ADS-1D-1Z': {'dimmer': 1, 'binary_sensor': 1},
    'ADS-2R-2Z': {'switch': 2, 'binary_sensor': 2},
    'AIR-PIR-CM': {'binary_sensor': 1},
    'VEN-4S-4R-HC': {},
    'VEN-AC-5R-LC': {},
    'VEN-AC-4R-HC': {},
    'AIR-1IRE-T': {'ac': 1},
    'AIR-2IRE': {'ac': 1},
    'ACM-2R-2Z': {'switch': 2, 'binary_sensor': 2},
    'VEN-2S-2R-HC': {},
    'VEN-AC-3R-HC': {},
    'ADS-4CH-0-10V': {'dimmer': 4},
    'ADS-3R-3Z': {'switch': 3, 'binary_sensor': 3},
    'AMP-5S1Z-MTX': {},
    'AIR-SOCKET-S': {},
    'VEN-1D-UV': {},
    'VEN-3S-3R-HC': {},
    'TIS-AIR-BUS': {},
    'PRJ-LFT-15K-130': {},
    'TIS-WS-71': {},
    'IP-COM-PORT': {},
    'MET-EN-1PH': {},
    'TIS-KNX-PORT': {},
    'TIS-TRV-16CNV': {},
    'LUNA-IN-HOTEL-HRF': {},
    'LUNA-IN-HOTEL-3T3L-HRF': {},
    'IO-IN-HOTEL-HRF': {},
    'LUNA-OUT-HOTEL-HRF': {},
    'LUNA-OUT-HOTEL': {},
    'IO-OUT-HOTEL-HRF': {},
    'IO-OUT-HOTEL': {},
    'TIS-MER-8G-PB': {'ac': 1},
    'TIS-MER-AC4G-PB': {},
    'IO-IN-HOTEL-LRF': {},
    'IO-OUT-HOTEL-LRF': {},
    'LUNA-IN-HOTEL-LRF': {},
    'LUNA-OUT-HOTEL-LRF': {},
    'LUNA-IN-HOTEL-3T3L-LRF': {},
    'TIS-ZIG-PORT': {},
    'TIS-AUD-SRV-4X-160W': {},
    'TIS-M7-CURTAIN': {'motor': 1},
    'VEN-2G-HC-BUS-B': {},
    'VEN-3G-HC-BUS-B': {},
    'VEN-4G-HC-BUS-B': {},
    'VEN-AC-3R-1.5-OLED-BUS': {'ac': 1},
    'VEN-AC-4R-1.5-OLED-BUS': {'ac': 1},
    'VEN-AC-5R-1.5-OLED-BUS': {'ac': 1},
    'VEN-AC-3R-1.5-OLED': {'ac': 1},
    'VEN-AC-4R-1.5-OLED': {'ac': 1},
    'VEN-AC-5R-1.5-OLED': {'ac': 1},
    'TIS-VRV-PRO': {},
    'VEN-2G-HC-AIR-A': {},
    'VEN-3G-HC-AIR-A': {},
    'VEN-4G-HC-AIR-A': {},
    'TIS-BEDSIDE-12G': {'ac': 1},
    'TIS-BUS-CONVERTER': {},
    'TIS-4CH-AIN': {},
    'TIS-OUTDOOR-BELL': {},
    'TIS-SOL-3G': {},
    'MER-IN-HOTEL-LRF': {},
    'TER-2G': {},
    'TIS-SOL-TFT': {'ac': 1},
    'MER-OUT-HOTEL-LRF': {},
    'TIS-GTY-1AC': {},
    'IO-OUT-HOTEL-HRF-809A': {},
    'IO-OUT-HOTEL-809B': {},
    'LUNA-OUT-HOTEL-HRF-809C': {},
    'LUNA-OUT-HOTEL-809D': {},
    'IO-IN-HOTEL-HRF-809E': {},
    'CLICK-1G-PANEL-BUS': {},
    'CLICK-2G-PANEL-BUS': {},
    'CLICK-3G-PANEL-BUS': {},
    'CLICK-4G-PANEL-BUS': {},
    'CLICK-6G-PANEL-BUS': {},
    'TIS-SEC-PRO': {'switch': 1, 'binary_sensor': 4, 'security': 1},
    'TIS-CLICK-AC-BUS': {'ac': 1},
    'TIS-22DI-DIN': {'binary_sensor': 22},
    'MER-IN-HOTEL-HRF-0x80AA': {},
    'TIS-4AI-010V': {},
    'TIS-4AI-4-20MA': {},
    'MER-OUT-HOTEL-HRF-0x80AD': {},
    'TIS-HEALTH-CM-RADAR': {'binary_sensor': 1},
    'TIS-ZB-GATEWAY': {},
    'TIS-RADAR-SENSOR': {'binary_sensor': 2},
    'TIS-ERO-1G': {},
    'TIS-ERO-2G': {},
    'TIS-ERO-3G': {},
    'TIS-ERO-4G': {},
    'TIS-ERO-6G': {},
    'TIS-CLICK-AC-FH-BUS': {'ac': 1},
    'TIS-C-BUS-CONVERTER': {},
    'TIS-FAN-4CH': {'switch': 4},
    'TIS-SIR-4G': {},
    'TIS-SIR-6G': {},
    'TIS-SIR-8G': {},
    'TIS-TM-120': {'motor': 1},
}

